### ISSUE TITLE
FileNotFoundError after UnsupportedCompressionMethodError on specific files

### ISSUE THREAD

**Issue by zhbzhbzhbz** [miurahr/py7zr#218]
**Describe the bug**
FileNotFoundError occured after UnsupportedCompressionMethodError on a few files

**To Reproduce**
1. run "py7zr x test.7z"
2. See error

On Centos:
```
[hongbo@wgz1 ~]$ py7zr x test.7z 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hongbo/.local/lib/python3.8/site-packages/py7zr/py7zr.py", line 997, in extract_single
    crc32 = self.decompress(fp, f.folder, ofp, f.uncompressed, f.compressed, src_end)
  File "/home/hongbo/.local/lib/python3.8/site-packages/py7zr/py7zr.py", line 1027, in decompress
    decompressor = folder.get_decompressor(compressed_size)
  File "/home/hongbo/.local/lib/python3.8/site-packages/py7zr/archiveinfo.py", line 390, in get_decompressor
    self.decompressor = SevenZipDecompressor(self.coders, packsize, self.unpacksizes, self.crc, self.password)
  File "/home/hongbo/.local/lib/python3.8/site-packages/py7zr/compressor.py", line 714, in __init__
    self.methods_map = [SupportedMethods.is_native_coder(coder) for coder in coders]  # type: List[bool]
  File "/home/hongbo/.local/lib/python3.8/site-packages/py7zr/compressor.py", line 714, in <listcomp>
    self.methods_map = [SupportedMethods.is_native_coder(coder) for coder in coders]  # type: List[bool]
  File "/home/hongbo/.local/lib/python3.8/site-packages/py7zr/compressor.py", line 968, in is_native_coder
    raise UnsupportedCompressionMethodError
py7zr.exceptions.UnsupportedCompressionMethodError
Traceback (most recent call last):
  File "/usr/local/bin/py7zr", line 11, in <module>
    sys.exit(main())
  File "/home/hongbo/.local/lib/python3.8/site-packages/py7zr/__main__.py", line 25, in main
    return cli.Cli().run()
  File "/home/hongbo/.local/lib/python3.8/site-packages/py7zr/cli.py", line 91, in run
    return args.func(args)
  File "/home/hongbo/.local/lib/python3.8/site-packages/py7zr/cli.py", line 296, in run_extract
    a.extractall(callback=cb)
  File "/home/hongbo/.local/lib/python3.8/site-packages/py7zr/py7zr.py", line 629, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "/home/hongbo/.local/lib/python3.8/site-packages/py7zr/py7zr.py", line 764, in _extract
    os.utime(str(outfilename), times=(creationtime, creationtime))
FileNotFoundError: [Errno 2] No such file or directory
```
On Windows10:
```
Traceback (most recent call last):
  File "d:\program files\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "d:\program files\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "d:\program files\python38\lib\site-packages\py7zr\py7zr.py", line 997, in extract_single
    crc32 = self.decompress(fp, f.folder, ofp, f.uncompressed, f.compressed, src_end)
  File "d:\program files\python38\lib\site-packages\py7zr\py7zr.py", line 1027, in decompress
    decompressor = folder.get_decompressor(compressed_size)
  File "d:\program files\python38\lib\site-packages\py7zr\archiveinfo.py", line 390, in get_decompressor
    self.decompressor = SevenZipDecompressor(self.coders, packsize, self.unpacksizes, self.crc, self.password)
  File "d:\program files\python38\lib\site-packages\py7zr\compressor.py", line 714, in __init__
    self.methods_map = [SupportedMethods.is_native_coder(coder) for coder in coders]  # type: List[bool]
  File "d:\program files\python38\lib\site-packages\py7zr\compressor.py", line 714, in <listcomp>
    self.methods_map = [SupportedMethods.is_native_coder(coder) for coder in coders]  # type: List[bool]
  File "d:\program files\python38\lib\site-packages\py7zr\compressor.py", line 968, in is_native_coder
    raise UnsupportedCompressionMethodError
py7zr.exceptions.UnsupportedCompressionMethodError
Traceback (most recent call last):
  File "d:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python38\Scripts\py7zr.exe\__main__.py", line 7, in <module>
  File "d:\program files\python38\lib\site-packages\py7zr\__main__.py", line 25, in main
    return cli.Cli().run()
  File "d:\program files\python38\lib\site-packages\py7zr\cli.py", line 91, in run
    return args.func(args)
  File "d:\program files\python38\lib\site-packages\py7zr\cli.py", line 296, in run_extract
    a.extractall(callback=cb)
  File "d:\program files\python38\lib\site-packages\py7zr\py7zr.py", line 629, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "d:\program files\python38\lib\site-packages\py7zr\py7zr.py", line 764, in _extract
    os.utime(str(outfilename), times=(creationtime, creationtime))
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'a2002ToolBox\\PlugIn\\Core.dll'
```

**Expected behavior**
Only "py7zr.exceptions.UnsupportedCompressionMethodError" showed **without** "[Errno 2] No such file or directory" or "FileNotFoundError: [WinError 2] 系统找不到指定的文件" 

For example, when running "py7zr x test2.7z", it only shows "Unsupported compression method is used in archive. ABORT". 
And when running extractall() on test2.7z, it only shows "py7zr.exceptions.UnsupportedCompressionMethodError"

**Environment (please complete the following information):**
 - OS: Windows 10/Centos7.8
 - Python 3.8
 - py7zr version: 0.9.4

[test.zip](https://github.com/miurahr/py7zr/files/5054504/test.zip)
[test2.zip](https://github.com/miurahr/py7zr/files/5054562/test2.zip)

**Comment by miurahr** [comment]
When multi-threading extraction, parent thread fails to catch extraction thread exceptions.

**Comment by miurahr** [comment]
We can use  [threading.ExceptionHook()](https://docs.python.org/3/library/threading.html#threading.excepthook) in Python 3.8.
But we also need to handle it in Python 3.5-3.7 and PyPy3.

**Comment by miurahr** [comment]
Does #219 solve your issue? @zhbzhbzhbz 
I've used your test case as regression test.

**Comment by miurahr** [comment]
I'd like to add more comment here.

The case @zhbzhbzhbz provided uses LZMA2, LZMA1 + BCJ2. And BCJ2 is not supported in py7zr.
If anyone write and push the BCJ2 filter in Python,  we can support it.

**Comment by zhbzhbzhbz** [comment]
> We can use [threading.ExceptionHook()](https://docs.python.org/3/library/threading.html#threading.excepthook) in Python 3.8.
> But we also need to handle it in Python 3.5-3.7 and PyPy3.

yes, I use ```threading.ExceptionHook()``` in my project. And in order to reduce the workload, I wrote in the README, "The minimum version required of python is 3.8". lol.

**Comment by miurahr** [comment]
#219 implements without threading.ExceptionHook().

**Comment by zhbzhbzhbz** [comment]
> Does #219 solve your issue? @zhbzhbzhbz
> I've used your test case as regression test.

test.7z is ok, but another file still encountered this problem
[test3.zip](https://github.com/miurahr/py7zr/files/5055540/test3.zip)

**Comment by miurahr** [comment]
> test.7z is ok, but another file still encountered this problem. Sorry to trouble you
test3.zip

I've added the case but I cannot reproduce it.(renamed issue_218_2.7z)
A file is compressed with LZMA+BCJ2 which is not supported by py7zr and python core library.

**Comment by zhbzhbzhbz** [comment]
> > test.7z is ok, but another file still encountered this problem. Sorry to trouble you
> > test3.zip
> 
> I've added the case but I cannot reproduce it.(renamed issue_218_2.7z)
> A file is compressed with LZMA+BCJ2 which is not supported by py7zr and python core library.

sorry, my mistake. The error should be: object of type '_io.BufferedReader' has no len()
I just tried it again on Windows 10 and Centos7
```
[hongbo@wgz1 ~]$ wget "https://github.com/miurahr/py7zr/files/5055540/test3.zip" && unzip test3.zip
[hongbo@wgz1 ~]$ wget "http://raw.githubusercontent.com/miurahr/py7zr/87a41e49be85d0cbdedd7ff80a08d9ccca12f519/py7zr/py7zr.py" -P /home/hongbo/.local/lib/python3.8/site-packages/py7zr
[hongbo@wgz1 ~]$ py7zr x test3.7z
Unsupported compression method is used in archive. ABORT.
[hongbo@wgz1 ~]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.8.2003 (Core)
Release:	7.8.2003
Codename:	Core
[hongbo@wgz1 ~]$ py7zr --version
py7zr Version 0.9.4 : Copyright (C) 2019,2020 Hiroshi Miura (Python 3.8.5 [CPython GCC 4.8.5 20150623 (Red Hat 4.8.5-39)])
```

But on Windows10 (Manual):
```
first, download https://raw.githubusercontent.com/miurahr/py7zr/87a41e49be85d0cbdedd7ff80a08d9ccca12f519/py7zr/py7zr.py and replace the older file, then in the cmd:

C:\Users\potter\Desktop>python
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import py7zr
>>> with py7zr.SevenZipFile("test3.7z", mode='r') as archive:
...             archive.extractall()
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "D:\Program Files\Python38\lib\site-packages\py7zr\py7zr.py", line 629, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "D:\Program Files\Python38\lib\site-packages\py7zr\py7zr.py", line 735, in _extract
    self.worker.extract(self.fp, parallel=(not self.password_protected and not self._filePassed))
  File "D:\Program Files\Python38\lib\site-packages\py7zr\py7zr.py", line 982, in extract
    raise exc_type(exc_val).with_traceback(exc_tb)
  File "D:\Program Files\Python38\lib\site-packages\py7zr\py7zr.py", line 1005, in extract_single
    crc32 = self.decompress(fp, f.folder, ofp, f.uncompressed, f.compressed, src_end)
  File "D:\Program Files\Python38\lib\site-packages\py7zr\py7zr.py", line 1043, in decompress
    tmp = decompressor.decompress(fp, out_remaining)
  File "D:\Program Files\Python38\lib\site-packages\py7zr\compressor.py", line 761, in decompress
    self.consumed += len(data)
TypeError: object of type '_io.BufferedReader' has no len()
```

**Comment by miurahr** [comment]
In python 0.9.4,  `  File "D:\Program Files\Python38\lib\site-packages\py7zr\py7zr.py", line 1043, in decompress`

is 
```
                    read_size = min(READ_BLOCKSIZE - decompressor.unused_size, rest_size)
                    inp = fp.read(read_size)
                    tmp = decompressor.decompress(inp, max_length)
```

not
```
    tmp = decompressor.decompress(fp, out_remaining)`
```

Which py7zr version do you use?

**Comment by miurahr** [comment]
CI Test on windows are passed; https://github.com/miurahr/py7zr/pull/219/checks?check_run_id=970353298

**Comment by zhbzhbzhbz** [comment]
> In py7zr v0.9.4, ` File "D:\Program Files\Python38\lib\site-packages\py7zr\py7zr.py", line 1043, in decompress`
> 
> is
> 
> ```
>                     read_size = min(READ_BLOCKSIZE - decompressor.unused_size, rest_size)
>                     inp = fp.read(read_size)
>                     tmp = decompressor.decompress(inp, max_length)
> ```
> 
> not
> 
> ```
>     tmp = decompressor.decompress(fp, out_remaining)`
> ```
> 
> Which py7zr version do you use?

C:\Users\potter>py7zr --version
py7zr Version 0.9.4 : Copyright (C) 2019,2020 Hiroshi Miura (Python 3.8.5 [CPython MSC v.1924 64 bit (AMD64)])

But in order to test your pr, the py7zr.py I used is from "https://github.com/miurahr/py7zr/blob/87a41e49be85d0cbdedd7ff80a08d9ccca12f519/py7zr/py7zr.py"

**Comment by miurahr** [comment]
> But in order to test your pr, the py7zr.py is replaced by the one in #219,

#219 is PR against master, v0.10.*. so the error you report is because you merge a part of v0.10 code into v0.9.4 code.

**Comment by miurahr** [comment]
v0.9.5 and v0.10.0a2 is out with a fix.

**Comment by zhbzhbzhbz** [comment]
> v0.9.5 and v0.10.0a2 is out with a fix.
> 
> https://pypi.org/project/py7zr/#history

thx~ v0.9.5 works well.

**Comment by zhbzhbzhbz** [comment]
> v0.9.5 and v0.10.0a2 is out with a fix.
> 
> https://pypi.org/project/py7zr/#history

thx~ v0.9.5 works well.

**Comment by LeiGuo-code** [comment]
I have the same error.

>  d:\temp>py7zr x "test.7z"
Unsupported compression method is used in archive. ABORT.

And I try to extractall by python.
The error is 

> raise UnsupportedCompressionMethodError
py7zr.exceptions.UnsupportedCompressionMethodError
