### ISSUE TITLE
SevenZipFile() crashed when no password provided against header encrypted archive

### ISSUE THREAD

**Issue by miurahr** [miurahr/py7zr#234]
**Describe the bug**

@freddrake report in another ticket;

> When attempting to open a 7-zip file with an encrypted header, I get the following exception if I don't provide the password:

~~~~~~ text
Traceback (most recent call last):
  ...
    zf = py7zr.SevenZipFile(bytesio, mode='r')
  File ".../py7zr/py7zr.py", line 345, in __init__
    raise e
  File ".../py7zr/py7zr.py", line 318, in __init__
    self._real_get_contents(password)
  File ".../py7zr/py7zr.py", line 373, in _real_get_contents
    header = Header.retrieve(self.fp, buffer, self.afterheader, password)
  File ".../py7zr/archiveinfo.py", line 850, in retrieve
    obj._read(fp, buffer, start_pos, password)
  File ".../py7zr/archiveinfo.py", line 883, in _read
    decompressor = folder.get_decompressor(compressed_size)
  File ".../py7zr/archiveinfo.py", line 390, in get_decompressor
    self.decompressor = SevenZipDecompressor(self.coders, packsize, self.unpacksizes, self.crc, self.password)
  File ".../py7zr/compressor.py", line 743, in __init__
    self.cchain.add_filter(get_alternative_decompressor(coders[i], unpacksizes[i], password))
  File ".../py7zr/compressor.py", line 600, in get_alternative_decompressor
    return algorithm_class_map[filter_id][1](coder['properties'], password)
  File ".../py7zr/compressor.py", line 168, in __init__
    key = calculate_key(password.encode('utf-16LE'), numcyclespower, salt, 'sha256')
AttributeError: 'NoneType' object has no attribute 'encode'
~~~~~~

When no password is provided, would it be reasonable to raise `py7zr.PasswordRequired` here?

**Related issue**
#208, #231  

**Expected behavior***
 it is reasonable to raise `py7zr.PasswordRequired` here.

**Comment by miurahr** [comment]
@freddrake Could you provide test data to reproduce the issue?


I've added[ the test](https://github.com/miurahr/py7zr/commit/efe9055b424e283d6a8a155cb5e157a2be7988b4)  which try to extract header encrypted archive without password, and expect catch `py7zr.PasswordRquired` exception. 

It is just passed.

**Comment by freddrake** [comment]
Sample document that exhibits the described behavior, gizipped so GitHub will accept it:
[sample-docs-header.7z.gz](https://github.com/miurahr/py7zr/files/5210278/sample-docs-header.7z.gz)

Tested with **py7zr** 0.9.5 on Python 3.8.

~~~~~~ python
>>> import py7zr
>>> 
>>> py7zr.SevenZipFile('sample-docs-header.7z')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/KEEPERTECH/fdrake/Documents/sevenziptest/lib/python3.8/site-packages/py7zr/py7zr.py", line 345, in __init__
    raise e
  File "/home/KEEPERTECH/fdrake/Documents/sevenziptest/lib/python3.8/site-packages/py7zr/py7zr.py", line 318, in __init__
    self._real_get_contents(password)
  File "/home/KEEPERTECH/fdrake/Documents/sevenziptest/lib/python3.8/site-packages/py7zr/py7zr.py", line 373, in _real_get_contents
    header = Header.retrieve(self.fp, buffer, self.afterheader, password)
  File "/home/KEEPERTECH/fdrake/Documents/sevenziptest/lib/python3.8/site-packages/py7zr/archiveinfo.py", line 850, in retrieve
    obj._read(fp, buffer, start_pos, password)
  File "/home/KEEPERTECH/fdrake/Documents/sevenziptest/lib/python3.8/site-packages/py7zr/archiveinfo.py", line 883, in _read
    decompressor = folder.get_decompressor(compressed_size)
  File "/home/KEEPERTECH/fdrake/Documents/sevenziptest/lib/python3.8/site-packages/py7zr/archiveinfo.py", line 390, in get_decompressor
    self.decompressor = SevenZipDecompressor(self.coders, packsize, self.unpacksizes, self.crc, self.password)
  File "/home/KEEPERTECH/fdrake/Documents/sevenziptest/lib/python3.8/site-packages/py7zr/compressor.py", line 743, in __init__
    self.cchain.add_filter(get_alternative_decompressor(coders[i], unpacksizes[i], password))
  File "/home/KEEPERTECH/fdrake/Documents/sevenziptest/lib/python3.8/site-packages/py7zr/compressor.py", line 600, in get_alternative_decompressor
    return algorithm_class_map[filter_id][1](coder['properties'], password)
  File "/home/KEEPERTECH/fdrake/Documents/sevenziptest/lib/python3.8/site-packages/py7zr/compressor.py", line 168, in __init__
    key = calculate_key(password.encode('utf-16LE'), numcyclespower, salt, 'sha256')
AttributeError: 'NoneType' object has no attribute 'encode'
~~~~~~

**Comment by miurahr** [comment]
A header of test data indicate a encode method.
```
003470 17 06 b3 a0 01 09 80 b0 00 07 0b 01 00 01 24 06
003480 f1 07 01 0a 53 07 01 a0 ce 30 2e 5c 2c 3e 0c 80
003490 a2 0a 01 01 bb 78 35 00 00
```
- encode header id (0x17)
- packinfo id (0x06)
- pack position (0xb3 0xa0)
- number of pack stream (0x01)
- size id (0x09)
- size (0x80 b0)
- end id (0x00)
- unpack info id(0x07)
- folder id (0x0b)
- number of folder (0x01)
- internal/external (0x00) = internal
- **number of coder (0x01)**
- coder flags  (0x24)  => ID length = 4
- **coder ID (b'06f10701') => 7zAES**
- property size (0x0a)
- property (0x530701a0ce302e5c2c3e)
- coder unpack size id (0x0c)
- size (0x80 0xa2)
- CRC id(0x0a)
- digest defined (0x01)
- digest (0x01 0xbb 0x78 0x35) = 0x3578bb01
- end id(0x00)
- end id(0x00)

We can find a fact from analysis;  the file header is encrypted with AES without any compression (ex. LZMA2).

Previous test data is encrypted with AES+LZMA2. Here is a difference.

**Comment by miurahr** [comment]
password and crypt check is placed in 
https://github.com/miurahr/py7zr/blob/master/py7zr/compressor.py#L618-L619
```
618                if SupportedMethods.is_crypto_id(filter_id) and password is None:
619                    raise PasswordRequired("Password is required for extracting given archive.")
```
that is in if block:
https://github.com/miurahr/py7zr/blob/master/py7zr/compressor.py#L602
```
602  if len(coders) >= 2
```

It cause your test data pass the above check because len(coders) == 1.

**Comment by miurahr** [comment]
Start PR #237

**Comment by miurahr** [comment]
v0.10.0a6 and v0.9.7 released.
