### ISSUE TITLE
UnsupportedCompressionMethodError

### ISSUE THREAD

**Issue by Rhythmicc** [miurahr/py7zr#284]
**Environment (please complete the following information):**
 - OS: Mac OS 11
 - Python 3.8.1
 - py7zr version: latest

**Try do:**
```python3
>>> import py7zr
>>> with py7zr.SevenZipFile('Clash.for.Windows-0.14.1-mac.7z', 'r') as f:
...     f.extractall()
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py7zr/py7zr.py", line 835, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py7zr/py7zr.py", line 540, in _extract
    self.worker.extract(self.fp, parallel=(not self.password_protected and not self._filePassed))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py7zr/py7zr.py", line 1041, in extract
    raise exc_type(exc_val).with_traceback(exc_tb)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py7zr/py7zr.py", line 1068, in extract_single
    crc32 = self.decompress(fp, f.folder, ofp, f.uncompressed, f.compressed, src_end)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py7zr/py7zr.py", line 1111, in decompress
    decompressor = folder.get_decompressor(compressed_size)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py7zr/archiveinfo.py", line 388, in get_decompressor
    self.decompressor = SevenZipDecompressor(self.coders, packsize, self.unpacksizes, self.crc, self.password)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py7zr/compressor.py", line 695, in __init__
    self.methods_map = [SupportedMethods.is_native_coder(coder) for coder in coders]  # type: List[bool]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py7zr/compressor.py", line 695, in <listcomp>
    self.methods_map = [SupportedMethods.is_native_coder(coder) for coder in coders]  # type: List[bool]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py7zr/compressor.py", line 1041, in is_native_coder
    raise UnsupportedCompressionMethodError
py7zr.exceptions.UnsupportedCompressionMethodError
```

**Test data(please attach in the report):**
You can get the test data from here: https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.14.1/Clash.for.Windows-0.14.1-mac.7z

**Additional context**
I hope the boss will work harder to support another compression method. QAQ

**Comment by miurahr** [comment]
It use BCJ2 filter that is not supported by Python, so py7zr also does not support it.
