### ISSUE TITLE
py7zr.exceptions.Bad7zFile: CRC32 error on archived file

### ISSUE THREAD

**Issue by stahh** [miurahr/py7zr#313]
I can't attach a 7z archive. But it's just regular archive. I took 2 txt files and compressed them with system archive manager. Then tried extract files with system 7z cli, and it works.
Note: extract_all works as expected

![sys_info](https://user-images.githubusercontent.com/9351796/110082608-40c2b280-7d96-11eb-8cdd-39392c7621fe.png)

py7zr==0.14.1
Python 3.8.0 (default, Oct 28 2019, 16:14:01)  

/usr/bin/python3.8 py7zr_bug.py
2021-03-05 09:27:12,755  INFO  py7zr_bug.py  23  Unpack 7zip: py7zr_bug.7z
2021-03-05 09:27:12,758  ERROR  py7zr_bug.py  30  Bad7zFile('CRC32 error on archived file requirements.txt.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/py7zr/py7zr.py", line 552, in _extract
    self.worker.extract(self.fp, parallel=(not self.password_protected and not self._filePassed))
  File "/usr/local/lib/python3.8/dist-packages/py7zr/py7zr.py", line 1073, in extract
    self.extract_single(fp, self.files, self.src_start, src_end, q, skip_notarget=skip_notarget)
  File "/usr/local/lib/python3.8/dist-packages/py7zr/py7zr.py", line 1149, in extract_single
    raise e
  File "/usr/local/lib/python3.8/dist-packages/py7zr/py7zr.py", line 1128, in extract_single
    self._check(fp, just_check, src_end)
  File "/usr/local/lib/python3.8/dist-packages/py7zr/py7zr.py", line 1160, in _check
    raise CrcError("{}".format(f.filename))
py7zr.exceptions.CrcError: requirements.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Help_Archive/py7zr_bug.py", line 27, in main
    zip7.extract(path='.', targets=[f])
  File "/usr/local/lib/python3.8/dist-packages/py7zr/py7zr.py", line 865, in extract
    self._extract(path, targets, return_dict=False)
  File "/usr/local/lib/python3.8/dist-packages/py7zr/py7zr.py", line 554, in _extract
    raise Bad7zFile("CRC32 error on archived file {}.".format(str(ce)))
py7zr.exceptions.Bad7zFile: CRC32 error on archived file requirements.txt.

Process finished with exit code 0

py7zr_bug.py
--------------------------------

```
import py7zr
import warnings
import logging
import sys

LOG_LEVEL = 'INFO'
warnings.simplefilter("ignore")


def get_logger():
    logger = logging.getLogger()
    logger.setLevel(LOG_LEVEL)
    formatter = logging.Formatter(
            '%(asctime)s  %(levelname)s  %(filename)s  %(lineno)s  %(message)s')
    stream = logging.StreamHandler(sys.stdout)
    stream.setFormatter(formatter)
    logger.addHandler(stream)
    return logger


def main(f_name):
    try:
        logger.info(f'Unpack 7zip: {f_name}')
        zip7 = py7zr.SevenZipFile(f_name)
        files = zip7.getnames()
        for f in files:
            zip7.extract(path='.', targets=[f])
        return True
    except Exception as e:
        logger.exception(repr(e))
        return False


if __name__ == '__main__':
    logger = get_logger()
    main('py7zr_bug.7z')
```

**Comment by miurahr** [comment]
Multiple call of extract() is not  permitted.

bad
```
         for f in files:
            zip7.extract(path='.', targets=[f])
```

works
```
     targets = []
     for f in files:
         if your_logic(f):
               targets.append(f)
    zip7.extract(targets=targets)
```

**Comment by stahh** [comment]
Thank you, it works. Is this described in docs? Probably I skipped this and used extract like for zipfile.

**Comment by miurahr** [comment]
https://py7zr.readthedocs.io/en/latest/api.html#py7zr.SevenZipFile.extract
