### ISSUE TITLE
Read error from an appended archive that was empty

### ISSUE THREAD

**Issue by XP1** [miurahr/py7zr#369]
**Describe the bug**
`archive.readall()` throws exception:
```
Traceback (most recent call last):
  File "a.py", line 13, in <module>
    for name, bio in archive.readall().items():
  File "\py7zr\py7zr.py", line 947, in readall
    return self._extract(path=None, return_dict=True)
  File "\py7zr\py7zr.py", line 613, in _extract
    self.worker.extract(
  File "\py7zr\py7zr.py", line 1205, in extract
    if not any([self.target_filepath.get(f.id, None) for f in folders[i].files]):
TypeError: 'NoneType' object is not iterable
```

**To Reproduce**
```
import py7zr

with py7zr.SevenZipFile("Archive.7z", "w"):
    pass

with py7zr.SevenZipFile("Archive.7z", "a") as archive:
    archive.writestr("Test", arcname="Test/Test.txt")

with py7zr.SevenZipFile("Archive.7z", "r") as archive:
    names = archive.getnames()
    print(names)

    for name, bio in archive.readall().items():
        print(name, bio)
```

**Environment (please complete the following information):**
Windows 10, Python 3.9.7, py7zr 0.16.2

**Comment by XP1** [comment]
Also getting corrupt archive produced and freezing on `archive.test()` and `archive.readall()`.

```
import py7zr

with py7zr.SevenZipFile("Archive.7z", "w"):
    pass

with py7zr.SevenZipFile("Archive.7z", "a") as archive:
    print("Append 1")
    archive.writestr("Test", arcname="Test/Test.txt")

with py7zr.SevenZipFile("Archive.7z", "a") as archive:
    print("Append 2")
    archive.writestr("A", arcname="a/0/a.html")
    archive.writestr("B", arcname="a/0/b.json")
    archive.writestr("C", arcname="a/0/c.json")

with py7zr.SevenZipFile("Archive.7z", "a") as archive:
    print("Append 3")
    archive.writestr("A", arcname="b/0/a.html")
    archive.writestr("B", arcname="b/0/b.json")
    archive.writestr("C", arcname="b/0/c.json")

with py7zr.SevenZipFile("Archive.7z", "r") as archive:
    print("Read")
    print(archive.test(), archive.testzip())

    names = archive.getnames()
    print(names)

    for name, bio in archive.readall().items():
        print(name, bio)
```

**Comment by miurahr** [comment]
Thank you.
I've just reproduced the case in #372

**Comment by miurahr** [comment]
#372passed and it resolved the case.
