### ISSUE TITLE
32-bit Python gives `SystemError: deallocated bytearray object has exported buffers` --> `MemoryError`

### ISSUE THREAD

**Issue by ddalcino** [miurahr/py7zr#370]
**Describe the bug**
When I run `py7zr` with 32-bit Python 3.10.0 on Windows 10 on a large file (the qtwebengine file from Qt 6.2.0), I get a `SystemError: deallocated bytearray object has exported buffers` exception and a `MemoryError` exception.

**Related issue**
https://github.com/miurahr/aqtinstall/issues/436#issuecomment-955047368

**To Reproduce**
1. Download qtwebengine here: https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt6_620/qt.qt6.620.addons.qtwebengine.win64_msvc2019_64/6.2.0-0-202109261527qtwebengine-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z
2. Use 32-bit Python 3.10.0 on Windows 10 to extract the file, using this command:

```
python -m py7zr x 6.2.0-0-202109261527qtwebengine-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z
```

3. See error:

```console
> python -m py7zr x D:\Downloads\6.2.0-0-202109261527qtwebengine-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z
SystemError: deallocated bytearray object has exported buffers
Traceback (most recent call last):
  File "D:\Users\dave\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Users\dave\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\__main__.py", line 29, in <module>
    sys.exit(main())
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\__main__.py", line 25, in main
    return cli.Cli().run()
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\cli.py", line 99, in run
    return args.func(args)
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\cli.py", line 358, in run_extract
    a.extractall(callback=cb)
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\py7zr.py", line 955, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\py7zr.py", line 613, in _extract
    self.worker.extract(
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\py7zr.py", line 1172, in extract
    self.extract_single(
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\py7zr.py", line 1283, in extract_single
    raise e
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\py7zr.py", line 1268, in extract_single
    crc32 = self.decompress(fp, f.folder, ofp, f.uncompressed, f.compressed, src_end)
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\py7zr.py", line 1320, in decompress
    tmp = decompressor.decompress(fp, out_remaining)
  File "D:\Documents\PycharmProjects\aqtinstall\venv_32w\lib\site-packages\py7zr\compressor.py", line 648, in decompress
    res = self._buf[self._pos :] + tmp[: max_length - current_buf_len]
MemoryError
```

**Expected behavior**
I expected the archive to decompress without any error messages.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python 3.10.0, 32-bit
 - py7zr version: 0.16.2

**Comment by miurahr** [comment]
Thank you for the reproducer.
Unfortunately I don't have any idea how to look into memory allocation in 32bit python... It may be possible to run remote debuger and reproduce it on VM...

**Comment by miurahr** [comment]
ref: https://dzone.com/articles/python-memory-issues-tips-and-tricks

**Comment by miurahr** [comment]
Here is a memory profiling result when extracting the reported qt archive file on 64bit Linux.
Obviously increasing memory consumption during extraction.

![memory_profile_py7zr_qt620](https://user-images.githubusercontent.com/123720/140023632-9e3062a4-32b1-448d-8148-5c4af7581647.png)

**Comment by miurahr** [comment]
Here is memory profiling of `_decompress` function where exception observed.

```

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
   608     25.5 MiB     25.5 MiB           1       @profile(stream = profp)
   609                                             def _decompress(self, data, max_length: int):
   610     25.8 MiB      0.0 MiB           2           for i, decompressor in enumerate(self.chain):
   611     25.5 MiB      0.0 MiB           1               if self._unpacked[i] < self._unpacksizes[i]:
   612     25.5 MiB      0.0 MiB           1                   if isinstance(decompressor, LZMA1Decompressor) or isinstance(decompressor, PpmdDecompressor):
   613     25.8 MiB      0.2 MiB           1                       data = decompressor.decompress(data, max_length)  # always give max_length for lzma1
   614                                                         else:
   615                                                             data = decompressor.decompress(data)
   616     25.8 MiB      0.0 MiB           1                   self._unpacked[i] += len(data)
   617                                                     elif len(data) == 0:
   618                                                         data = b""
   619                                                     else:
   620                                                         raise EOFError
   621     25.8 MiB      0.0 MiB           1           return data


Filename: /home/miurahr/Projects/Python/py7zr/.tox/mprof/lib/python3.9/site-packages/py7zr/compressor.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
   608     27.0 MiB     27.0 MiB           1       @profile(stream = profp)
   609                                             def _decompress(self, data, max_length: int):
   610     38.6 MiB      0.0 MiB           2           for i, decompressor in enumerate(self.chain):
   611     27.0 MiB      0.0 MiB           1               if self._unpacked[i] < self._unpacksizes[i]:
   612     27.0 MiB      0.0 MiB           1                   if isinstance(decompressor, LZMA1Decompressor) or isinstance(decompressor, PpmdDecompressor):
   613                                                             data = decompressor.decompress(data, max_length)  # always give max_length for lzma1
   614                                                         else:
   615     38.6 MiB     11.6 MiB           1                       data = decompressor.decompress(data)
   616     38.6 MiB      0.0 MiB           1                   self._unpacked[i] += len(data)
   617                                                     elif len(data) == 0:
   618                                                         data = b""
   619                                                     else:
   620                                                         raise EOFError
   621     38.6 MiB      0.0 MiB           1           return data


Filename: /home/miurahr/Projects/Python/py7zr/.tox/mprof/lib/python3.9/site-packages/py7zr/compressor.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
   608    156.1 MiB    156.1 MiB           1       @profile(stream = profp)
   609                                             def _decompress(self, data, max_length: int):
   610    343.2 MiB      0.0 MiB           2           for i, decompressor in enumerate(self.chain):
   611    156.1 MiB      0.0 MiB           1               if self._unpacked[i] < self._unpacksizes[i]:
   612    156.1 MiB      0.0 MiB           1                   if isinstance(decompressor, LZMA1Decompressor) or isinstance(decompressor, PpmdDecompressor):
   613                                                             data = decompressor.decompress(data, max_length)  # always give max_length for lzma1
   614                                                         else:
   615    343.2 MiB    187.1 MiB           1                       data = decompressor.decompress(data)
   616    343.2 MiB      0.0 MiB           1                   self._unpacked[i] += len(data)
   617                                                     elif len(data) == 0:
   618                                                         data = b""
   619                                                     else:
   620                                                         raise EOFError
   621    343.2 MiB      0.0 MiB           1           return data


Filename: /home/miurahr/Projects/Python/py7zr/.tox/mprof/lib/python3.9/site-packages/py7zr/compressor.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
   608    394.9 MiB    394.9 MiB           1       @profile(stream = profp)
   609                                             def _decompress(self, data, max_length: int):
   610    855.5 MiB      0.0 MiB           2           for i, decompressor in enumerate(self.chain):
   611    394.9 MiB      0.0 MiB           1               if self._unpacked[i] < self._unpacksizes[i]:
   612    394.9 MiB      0.0 MiB           1                   if isinstance(decompressor, LZMA1Decompressor) or isinstance(decompressor, PpmdDecompressor):
   613                                                             data = decompressor.decompress(data, max_length)  # always give max_length for lzma1
   614                                                         else:
   615    855.5 MiB    460.6 MiB           1                       data = decompressor.decompress(data)
   616    855.5 MiB      0.0 MiB           1                   self._unpacked[i] += len(data)
   617                                                     elif len(data) == 0:
   618                                                         data = b""
   619                                                     else:
   620                                                         raise EOFError
   621    855.5 MiB      0.0 MiB           1           return data
```

**Comment by miurahr** [comment]
When memory consumption become peak;

```
Filename: /home/miurahr/Projects/Python/py7zr/.tox/mprof/lib/python3.9/site-packages/py7zr/compressor.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
   608    395.0 MiB    395.0 MiB           1       @profile(stream = profp)
   609                                             def _decompress(self, data, max_length: int):
   610    855.6 MiB      0.0 MiB           2           for i, decompressor in enumerate(self.chain):
   611    395.0 MiB      0.0 MiB           1               if self._unpacked[i] < self._unpacksizes[i]:
   612    395.0 MiB      0.0 MiB           1                   if isinstance(decompressor, LZMA1Decompressor) or isinstance(decompressor, PpmdDecompressor):
   613                                                             data = decompressor.decompress(data, max_length)  # always give max_length for lzma1
   614                                                         else:
   615    855.6 MiB    460.6 MiB           1                       data = decompressor.decompress(data)
   616    855.6 MiB      0.0 MiB           1                   self._unpacked[i] += len(data)
   617                                                     elif len(data) == 0:
   618                                                         data = b""
   619                                                     else:
   620                                                         raise EOFError
   621    855.6 MiB      0.0 MiB           1           return data


Filename: /home/miurahr/Projects/Python/py7zr/.tox/mprof/lib/python3.9/site-packages/py7zr/compressor.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
   623    311.0 MiB    311.0 MiB           1       @profile(stream = profp)
   624                                             def decompress(self, fp, max_length: int = -1) -> bytes:
   625                                                 # read data from disk
   626    311.0 MiB      0.0 MiB           1           rest_size = self.input_size - self.consumed
   627    311.0 MiB      0.0 MiB           1           read_size = min(rest_size, self.block_size)
   628    311.0 MiB      0.0 MiB           1           data = fp.read(read_size)
   629    311.0 MiB      0.0 MiB           1           self.consumed += len(data)
   630                                                 #
   631    311.0 MiB      0.0 MiB           1           if max_length < 0:
   632                                                     res = self._buf[self._pos :] + self._decompress(self._unused + data, max_length)
   633                                                     self._buf = bytearray()
   634                                                     self._unused = bytearray()
   635                                                     self._pos = 0
   636                                                 else:
   637    311.0 MiB      0.0 MiB           1               current_buf_len = len(self._buf) - self._pos
   638    311.0 MiB      0.0 MiB           1               if current_buf_len >= max_length:
   639                                                         self._unused.extend(data)
   640                                                         res = self._buf[self._pos : self._pos + max_length]
   641                                                         self._pos += max_length
   642                                                     else:
   643    311.0 MiB      0.0 MiB           1                   if len(self._unused) > 0:
   644    771.6 MiB    460.6 MiB           1                       tmp = self._decompress(self._unused + data, max_length)
   645    687.5 MiB    -84.1 MiB           1                       self._unused = bytearray()
   646                                                         else:
   647                                                             tmp = self._decompress(data, max_length)
   648    687.5 MiB      0.0 MiB           1                   if current_buf_len + len(tmp) <= max_length:
   649                                                             res = self._buf[self._pos :] + tmp
   650                                                             self._buf = bytearray()
   651                                                             self._pos = 0
   652                                                         else:
   653   1166.2 MiB    478.7 MiB           1                       res = self._buf[self._pos :] + tmp[: max_length - current_buf_len]
   654   1005.3 MiB   -160.9 MiB           1                       self._buf = bytearray(tmp[max_length - current_buf_len :])
   655   1005.3 MiB      0.0 MiB           1                       self._pos = 0
   656   1005.3 MiB      0.0 MiB           1           self.digest = calculate_crc32(res, self.digest)
   657   1005.3 MiB      0.0 MiB           1           return res
``` 

GiB of memory is used.

**Comment by miurahr** [comment]
The archive has a large, 500MiB, file;
```
2021-09-25 22:55:33 ....A    501920432               6.2.0/msvc2019_64/bin/Qt6WebEngineCored.dll
```
This may lead a huge memory consumption.

**Comment by miurahr** [comment]
When reduce buffer size from the default `1048576 bytes` to `32728 byte` that is for python 3.6, then memory consumption reduced.
![py7zr_reduce_buffer_size](https://user-images.githubusercontent.com/123720/140677059-69f32133-f896-4890-b78f-ddc3554ef170.png)

**Comment by ddalcino** [comment]
Whoa, how did you do that? I can try it locally for you, on 32 bit Windows python, to see if it resolves the problem.

**Comment by miurahr** [comment]
```
diff --git a/py7zr/properties.py b/py7zr/properties.py
index b354da5..f60f9c2 100644
--- a/py7zr/properties.py
+++ b/py7zr/properties.py
@@ -38,6 +38,8 @@ COMMAND_HELP_STRING = """<Commands>
 
 
 def get_default_blocksize():
+    if sys.maxsize <= 2**32:
+        return 32768
     if platform.python_implementation() == "PyPy" and sys.version_info >= (3, 6, 9):
         return 1048576
     elif sys.version_info >= (3, 7, 5):
```

I'd like to add it.

**Comment by miurahr** [comment]
Modification of #375 significantly reduce a  memory consumption peak.
![py7zr_only_when_read_unused_data_not_enough](https://user-images.githubusercontent.com/123720/140685020-5db80ba8-abc1-49a2-885e-ca016cdb49db.png)

**Comment by miurahr** [comment]
This is when both #374 and #375 effective

![py7zr_both_mods](https://user-images.githubusercontent.com/123720/140685568-106e8672-8f2d-478d-be61-719af46894ba.png)

**Comment by ddalcino** [comment]
> ```
> diff --git a/py7zr/properties.py b/py7zr/properties.py
> index b354da5..f60f9c2 100644
> --- a/py7zr/properties.py
> +++ b/py7zr/properties.py
> @@ -38,6 +38,8 @@ COMMAND_HELP_STRING = """<Commands>
>  
>  
>  def get_default_blocksize():
> +    if sys.maxsize <= 2**32:
> +        return 32768
>      if platform.python_implementation() == "PyPy" and sys.version_info >= (3, 6, 9):
>          return 1048576
>      elif sys.version_info >= (3, 7, 5):
> ```
> 
> I'd like to change it like this.

This change resolves the issue with 32-bit Python on Windows! 🎉
