### ISSUE TITLE
lzma missing in install_requires

### ISSUE THREAD

**Issue by areche** [miurahr/py7zr#382]
**Describe the bug**
When installing py7zr in a clean environment, importing the package fails with the following error:

```
Traceback (most recent call last):
  File "/home/areche/.virtualenvs/test-mlexporter/bin/mlexporter-cleandb", line 5, in <module>
    from marss.mlexporter.clean_db import main
  File "/home/areche/.virtualenvs/test-mlexporter/lib/python3.8/site-packages/marss/mlexporter/clean_db.py", line 4, in <module>
    from marss.mlexporter.tools import try_parsing_date
  File "/home/areche/.virtualenvs/test-mlexporter/lib/python3.8/site-packages/marss/mlexporter/tools.py", line 2, in <module>
    import py7zr
  File "/home/areche/.virtualenvs/test-mlexporter/lib/python3.8/site-packages/py7zr/__init__.py", line 21, in <module>
    from py7zr.properties import (
  File "/home/areche/.virtualenvs/test-mlexporter/lib/python3.8/site-packages/py7zr/properties.py", line 24, in <module>
    import lzma
  File "/home/areche/.pyenv/versions/3.8.12/lib/python3.8/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```

**To Reproduce**
(example)
1. `pip install` in clean environment
2. `python -c import py7zr`

**Expected behavior**
I will expect the package to install its dependencies

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - Python 3.8
 - py7zr version: 0.16.3

**Comment by areche** [comment]
The issue was not py7zr, but the python version installed by pyenv.

The solution was to uninstall the python version, install libzmla-dev, then reinstall python using pyenv again.

```
pyenv uninstall 3.8.12
apt-get install libzmla-dev
pyenv install 3.8.12
```

After that `py7zr` can be used normally.
