### ISSUE TITLE
UnsupportedCompressionMethodError: (b'\x03\x03\x01\x1b', 'Found an unknown id of method.')

### ISSUE THREAD

**Issue by hacki11** [miurahr/py7zr#408]
**Describe the bug**
Extracting a specific archive failes after many files could be extracted successfully.

**Related issue**
- https://github.com/miurahr/py7zr/issues/393
- 

**To Reproduce**
1. `wget https://github.com/oneclick/rubyinstaller/releases/download/ruby-2.1.9/ruby-2.1.9-x64-mingw32.7z`
2. `pip install -U py7zr --user`
3. `py7zr x ruby-2.1.9-x64-mingw32.7z`

**Expected behavior**
Extracts without errors

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python 3.10.2
 - py7zr version: py7zr-0.17.3-py3-none-any.whl

**Test data(please attach in the report):**
- see reproduce

**Additional context**
```
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\j.schmid\AppData\Roaming\Python\Python310\Scripts\py7zr.exe\__main__.py", line 7, in <module>
  File "C:\Users\j.schmid\AppData\Roaming\Python\Python310\site-packages\py7zr\__main__.py", line 25, in main
    return cli.Cli().run()
  File "C:\Users\j.schmid\AppData\Roaming\Python\Python310\site-packages\py7zr\cli.py", line 99, in run
    return args.func(args)
  File "C:\Users\j.schmid\AppData\Roaming\Python\Python310\site-packages\py7zr\cli.py", line 358, in run_extract
    a.extractall(callback=cb)
  File "C:\Users\j.schmid\AppData\Roaming\Python\Python310\site-packages\py7zr\py7zr.py", line 959, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "C:\Users\j.schmid\AppData\Roaming\Python\Python310\site-packages\py7zr\py7zr.py", line 621, in _extract
    self.worker.extract(
  File "C:\Users\j.schmid\AppData\Roaming\Python\Python310\site-packages\py7zr\py7zr.py", line 1238, in extract
    raise exc_type(exc_val).with_traceback(exc_tb)
TypeError: UnsupportedCompressionMethodError.__init__() missing 1 required positional argument: 'message'
```

**Comment by miurahr** [comment]
It is really unknown ID.
see: https://py7zr.readthedocs.io/en/latest/archive_format.html#codec-ids

What compression algorithm do you use?

**Comment by miurahr** [comment]
b'\x03\x03\x01\x1b' is BCJ2 that is not supported by Python,  so py7zr does not support it.

**Comment by miurahr** [comment]
We can add ID to document.

**Comment by miurahr** [comment]
Because py7zr knows the ID as unsupported_method, so py7zr should raise better message, not unknown one.
https://github.com/miurahr/py7zr/blob/d69a6381255b6c4266513904eb1f8b9b4c3cae05/py7zr/compressor.py#L1127-L1131

**Comment by miurahr** [comment]
Message improved and document updated.

**Comment by LuminairPrime** [comment]
I just ran into this too late. I assumed we supported BCJ2 because so much software uses it. The compression is very good. I can't even extract ffmpeg 7z :O https://github.com/GyanD/codexffmpeg/releases
