### ISSUE TITLE
OverflowError in archiveinfo.py

### ISSUE THREAD

**Issue by fdellwing** [miurahr/py7zr#41]
```
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    archive.close()
  File "/home/fade/PycharmProjects/mbPatchCreator/venv/lib/python3.7/site-packages/py7zr/py7zr.py", line 764, in close
    self._write_archive()
  File "/home/fade/PycharmProjects/mbPatchCreator/venv/lib/python3.7/site-packages/py7zr/py7zr.py", line 579, in _write_archive
    encoded=self.encoded_header_mode)
  File "/home/fade/PycharmProjects/mbPatchCreator/venv/lib/python3.7/site-packages/py7zr/archiveinfo.py", line 977, in write
    self.files_info.write(file)
  File "/home/fade/PycharmProjects/mbPatchCreator/venv/lib/python3.7/site-packages/py7zr/archiveinfo.py", line 854, in write
    self._write_times(file, Property.CREATION_TIME, 'creationtime')
  File "/home/fade/PycharmProjects/mbPatchCreator/venv/lib/python3.7/site-packages/py7zr/archiveinfo.py", line 775, in _write_times
    write_byte(fp, (num_defined * 8 + 2).to_bytes(1, byteorder='little'))
OverflowError: int too big to convert
```

The biggest file is a 7.7mb `.war` application. In sum the uncompressed files are 9.6mb.

**Comment by miurahr** [comment]
Which version do you use?

**Comment by miurahr** [comment]
Gocha. It should be UINT64 but code try to write as a BYTE.

**Comment by miurahr** [comment]
Here is another problem in write_uint64() for larger values.

**Comment by miurahr** [comment]
Work is in progress as #42

**Comment by miurahr** [comment]
Now released v0.5b2 with fixes bugs found here.
Cloud you try again with v0.5b2 and feedback a result with your case?

**Comment by fdellwing** [comment]
It does run through now, but it produces no valid 7z archiv:

```
7z l mbPatchCreator/patch251.7z 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=de_DE.UTF-8,Utf16=on,HugeFiles=on,64 bits,12 CPUs Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (906EA),ASM,AES-NI)

Scanning the drive for archives:
1 file, 8222762 bytes (8031 KiB)

Listing archive: mbPatchCreator/patch251.7z


ERROR: mbPatchCreator/patch251.7z : mbPatchCreator/patch251.7z
Open ERROR: Can not open the file as [7z] archive


ERRORS:
Unsupported feature
WARNINGS:
Unsupported feature


Errors: 1
```

**Comment by miurahr** [comment]
How can I reproduce your case? 
Could you mind to  put a minimum test case, pytest function and data, which can be bundled here in GPL?

**Comment by miurahr** [comment]
Overflow error happened on reporter environment are gone. 
I'd like to close here and ask @fdellwing to open a new issue ticket for another problem.

**Comment by fdellwing** [comment]
I'm in xmas vacation, will open new issue after I get back to work.
