### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by feiyangf** [miurahr/py7zr#592]
```
Traceback (most recent call last):
  File "111.py", line 44, in <module>
    print(archive.read(archive.getnames()[0]))
  File "/usr/python/lib/python3.7/site-packages/py7zr/py7zr.py", line 994, in read
    return self._extract(path=None, targets=targets, return_dict=True)
  File "/usr/python/lib/python3.7/site-packages/py7zr/py7zr.py", line 635, in _extract
    parallel=(not self.password_protected and not self._filePassed),
  File "/usr/python/lib/python3.7/site-packages/py7zr/py7zr.py", line 1242, in extract
    skip_notarget=skip_notarget,
  File "/usr/python/lib/python3.7/site-packages/py7zr/py7zr.py", line 1323, in extract_single
    raise e
  File "/usr/python/lib/python3.7/site-packages/py7zr/py7zr.py", line 1320, in extract_single
    self._extract_single(fp, files, path, src_end, q, skip_notarget)
  File "/usr/python/lib/python3.7/site-packages/py7zr/py7zr.py", line 1389, in _extract_single
    crc32 = self.decompress(fp, f.folder, obfp, f.uncompressed, f.compressed, src_end)
  File "/usr/python/lib/python3.7/site-packages/py7zr/py7zr.py", line 1444, in decompress
    tmp = decompressor.decompress(fp, min(out_remaining, max_block_size))
  File "/usr/python/lib/python3.7/site-packages/py7zr/compressor.py", line 697, in decompress
    tmp = self._decompress(data, max_length)
  File "/usr/python/lib/python3.7/site-packages/py7zr/compressor.py", line 653, in _decompress
    data = decompressor.decompress(data, max_length)
TypeError: decompress() takes exactly 1 argument (2 given)
```
我k8s上安装`py7zr==0.20.6`的版本，出现  `File “/usr/local/python3.7.5/lib/python3.7/lzma.py”，line27，in <module>`
     from _lzma import*
ModuleNotFoundError: No module named '_lzma'`的问题，然后`yum install -y xz-devel` 
```
yum install -y python-backports-lzma  pip3 install backports.lzma
pip3 install backports.lzma
```

```
from _lzma import *
from _lzma import _encode_filter_properties, _decode_filter_properties
```
修改为
```
try:
    from _lzma import *
    from _lzma import _encode_filter_properties, _decode_filter_properties
except ImportError:
    from backports.lzma import *
    from backports.lzma import _encode_filter_properties, _decode_filter_properties
```
 就出现上面的问题了，方法参数传递是2个，但是报参数传递错误

**Comment by miurahr** [comment]
py7zr is supported on python 3.9 and later.
The support for python 3.8 will be dropped in next release, and you are recommended to use Python 3.12.
Please try v1.0.o-rc1

**Comment by miurahr** [comment]
The error message in v0.20.6; 
```
  File "/usr/python/lib/python3.7/site-packages/py7zr/compressor.py", line 653, in _decompress
    data = decompressor.decompress(data, max_length)
TypeError: decompress() takes exactly 1 argument (2 given)
```
is shown in https://github.com/miurahr/py7zr/blob/v0.20.6/py7zr/compressor.py#L653
and `decompressor` is object with type 

```
        if lzma1:
            return LZMA1Decompressor(filters, unpacksize)
        else:
            return lzma.LZMADecompressor(format=lzma.FORMAT_RAW, filters=filters)
```

When `LZMADecompressor` has two argument and, the signature is introduced in python 3.5.

see https://docs.python.org/3.7/library/lzma.html#lzma.LZMADecompressor.decompress

When `LZMA1Decompressor` is defined as
```
def decompress(self, data: Union[bytes, bytearray, memoryview], max_length: int = -1) -> bytes:
```

so the error should not be happened.

**Comment by miurahr** [comment]
`backports.lzma` is the library  to backport python **3.3's** lzma library for python 2.
You should use properly installed python on your platform.
